version: '3'

services:
  eureka:
    build:
      context: ./microservice-discovery-eureka
    image: hulk/eureka
    container_name: eureka
    ports:
      - "8761:8761"
#    links:
#      - "redis:redis"
#      - "mysql:mysql"
#    depends_on:
#      - redis
#      - mysql
    networks:
      - hulk
#    volumes:
#      - /Users/jliu/develop/upload:/var/ijusai/data/upload
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#
##docker run -p 8080:8080 -t  -e spring.profiles.active=docker --link redis:redis --link mysql:mysql --net ijusai senjing/ijusai.web
#
  user-service:
    build:
      context: ./microservice-provider-user
    image: hulk/user-service
    container_name: user-service-1
    ports:
      - "8081:8081"
    links:
      - "eureka:eureka"
#      - "mysql:mysql"
    depends_on:
      - eureka
#      - mysql
#    volumes:
#      - /Users/jliu/develop/upload:/var/ijusai/data/upload
    networks:
      - hulk
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8081
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true" #eureka为注册中心是，使用docker需要指定docker宿主机的ip
      EUREKA_INSTANCE_IP_ADDRESS: 192.168.2.177 #eureka为注册中心是，使用docker需要指定docker宿主机的ip

  user-service-a:
    image: hulk/user-service
    ports:
      - "8082:8082"
    links:
      - "eureka:eureka"
    depends_on:
      - eureka
    networks:
      - hulk
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8082
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true" #eureka为注册中心是，使用docker需要指定docker宿主机的ip
      EUREKA_INSTANCE_IP_ADDRESS: 192.168.2.177 #eureka为注册中心是，使用docker需要指定docker宿主机的ip

#  movice-service:
#    build:
#      context: ./microservice-consumer-movie-feign
#    image: hulk/movice-service
#    container_name: movice-service-1
#    ports:
#      - "8020:8020"
#    links:
#      - "eureka:eureka"
#    depends_on:
#      - eureka
#    networks:
#      - hulk
#    environment:
#      SPRING_PROFILES_ACTIVE: docker


networks:
  hulk:
    driver: bridge