server:
  port: 8000
spring:
  application:
    name: microservice-provider-user    # 项目名称尽量用小写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的insert脚本
  #cloud注册中心
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-url:
#      discovery:
#        tags: foo=bar, baz, weight=2
  #分布式追踪
  sleuth:
    sampler:
      percentage: 0.6
  #zipkin 配置
  zipkin:
    base-url: http://localhost:9411
    enabled: true

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true

---
spring:
  profiles: docker

  zipkin:
    base-url: http://zipkin:9411

  #cloud注册中心
  cloud:
    consul:
      host: consul
      port: 8500

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/    # 指定注册中心的地址
